### ISSUE TITLE
Mising Library.cpp (Visual Studio 2013)

### ISSUE THREAD

**Issue by compiledtom** [castano/nvidia-texture-tools#218]
Hi, I downloaded a ZIP of the source and opened it with VS2013 on Windows 8.1

I opened the solution from the vc12 directory and tried to compile it, and I received the following errors:

Error	1	error C1083: Cannot open source file: '..\..\..\src\nvcore\Library.cpp': No such file or directory	D:\Projects\nvidia-texture-tools-master\project\vc12\nvcore\c1xx	nvcore
Error	2	error C1083: Cannot open include file: 'nvcore/Library.h': No such file or directory	D:\Projects\nvidia-texture-tools-master\src\nvtt\cuda\CudaUtils.cpp	26	1	nvtt

This is followed by several linker errors, but those are obviously caused by the missing source files. 

I tried compiling without Library.cpp and Library.h, but that was a mess.

**Comment by castano** [comment]
Hmm... ugh, I may have removed that file too quickly. I didn't realize it was necessary for the CUDA code path, which is not being maintained right now. I believe that if you compile it with CUDA disabled it should just work. I can probably add it back if you need it, or you can just comment out the isCudaDriverAvailable function and its calls in CudaUtils.cpp
