### ISSUE TITLE
Please support ARM64 (aarch64)

### ISSUE THREAD

**Issue by tbm** [castano/nvidia-texture-tools#224]
nvidia-texture-tools currently doesn't compile on 64-bit ARM (Aarch64, commonly known as ARM64).

I've created a patch which seems to work for me.

Note that I'm not sure about how to name NV_CPU_.  I used NV_CPU_ARM64 because most people use "ARM64" to refer to this platform, but technically it's called AARCH64, so maybe NV_CPU_AARCH64 would be better.

Let me know what you think.

**Comment by tbm** [comment]
I couldn't figure out how to attach a file, but here's the patch:

http://cyrius.com/tmp/0001-Add-support-for-ARM64-aarch64.patch

**Comment by tbm** [comment]
I noticed in another tool (nvidial-settings) that they call it AARCH64 (e.g. they had NV_CTRL_ARCHITECTURE_AARCH64), so maybe going with NV_CPU_AARCH64 would be best after all.

**Comment by castano** [comment]
Thanks for the patch!
