### ISSUE TITLE
Undefined behaviour with aggressive loop optimizations

### ISSUE THREAD

**Issue by lhw** [castano/nvidia-texture-tools#226]
```
[ 50%] Building CXX object src/nvtt/squish/CMakeFiles/squish.dir/fastclusterfit.cpp.o
In file included from /tmp/buildd/nvidia-texture-tools-2.1.0+git20150720+dfsg/src/nvtt/squish/simd.h:42:0,
                 from /tmp/buildd/nvidia-texture-tools-2.1.0+git20150720+dfsg/src/nvtt/squish/fastclusterfit.h:32,
                 from /tmp/buildd/nvidia-texture-tools-2.1.0+git20150720+dfsg/src/nvtt/squish/fastclusterfit.cpp:27:
/tmp/buildd/nvidia-texture-tools-2.1.0+git20150720+dfsg/src/nvtt/squish/simd_sse.h: In member function 'virtual void nvsquish::FastClusterFit::Compress3(void*)':
/tmp/buildd/nvidia-texture-tools-2.1.0+git20150720+dfsg/src/nvtt/squish/simd_sse.h:90:28: warning: iteration 16u invokes undefined behavior [-Waggressive-loop-optimizations]
   m_v = _mm_add_ps( m_v, v.m_v );
                            ^
/tmp/buildd/nvidia-texture-tools-2.1.0+git20150720+dfsg/src/nvtt/squish/fastclusterfit.cpp:146:22: note: containing loop
  for( int c0 = 0; c0 <= 16; c0++)
                      ^
```
Same for nvsquish::FastClusterFit::Compress4

Built with Debian unstable.

**Comment by labidus** [comment]
I made a pullrequest related to 2 problems, the second i found is related that in FastClusterFit & WeigthClusterFit, all the loop are not ok, they must use < 16 not <= 16, if 16 the array[16] <-- fail, because the array is just 16, max is 15 not 16.

**Comment by castano** [comment]
I believe you can ignore that warning. Reducing the range of the loops is
not the right solution. You can probably silence it skipping the add for
the last element, but that will make things slower. Another option is
increasing the size of the array. Either way, the incremented value is not
used after the last iteration, so it doesn't matter what value it takes.

On Fri, Aug 21, 2015 at 7:02 PM, Sylvain Rochette <notifications@github.com>
wrote:

> I made a pullrequest related to 2 problems, the second i found is related
> that in FastClusterFit & WeigthClusterFit, all the loop are not ok, they
> must use < 16 not <= 16, if 16 the array[16] <-- fail, because the array is
> just 16, max is 15 not 16.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/castano/nvidia-texture-tools/issues/226#issuecomment-133625983>
> .
>



-- 
Ignacio Castaño
castano@gmail.com

**Comment by lhw** [comment]
I just increased the array size for now to avoid the warning.
