### ISSUE TITLE
New release version

### ISSUE THREAD

**Issue by lhw** [castano/nvidia-texture-tools#227]
Quite a few changes have been incorporated since my last debian package was released. Since then the internal version seems to have been bumped to 2.1.0 even though the VERSIONS file says its last been edited 8 years ago which seems not quite right.
It would be nice if you could tag a release for 2.1.0 including the ARM64 support or a an even newer version number.

**Comment by StanleySweet** [comment]
Any news on that ? We are using an old version for 0 A.D. just because of that with lots of patches applied onto it.

**Comment by krytarowski** [comment]
Some games bundle nvtt as 3rd party software and we need to keep patching them all the time, as nvtt just recently gained NetBSD support in the upstream version. A release would help with that.

**Comment by ng-0** [comment]
Any news on this issue? I'm currently packaging 0ad and would like to unbundle nvt from it.
Since 2010 there were commits with "fixed memory leak" etc, I would recommend a new release to address these issues and to help the projects who currently apply lots of backported patches to your software.

**Comment by castano** [comment]
I've tagged a new release:

https://github.com/castano/nvidia-texture-tools/releases/tag/2.1.0

Hope this helps!

**Comment by esok** [comment]
I have been regularly updating from the github current source under CentOS
7 and all seems to be working well. At some point soon I'll take a stab at
packaging it as an RPM for Fedora and/or CentOS.

Eric

**Comment by GoaLitiuM** [comment]
Could use for another version bump at this point, the latest release is over two years old and doesn't support `-dds10` and `-ktx` and the new formats.
