### ISSUE TITLE
Unable to decompress or view FourCC: BC5U coded normal or shadow map DDS

### ISSUE THREAD

**Issue by PyroDevil** [castano/nvidia-texture-tools#232]
I tried to view and decompress the normal and shadow map in this file:
https://db.tt/oR1Qsf4k
But nvddsview and nvdecompress doesn't seem to decode those files correctly.

I have it running on Linux without cuda with the Intel Mesa 11.0.6 drivers of the ivybridge iGPU.

**Comment by castano** [comment]
Sorry, I left some testing code in nvdecompress by mistake, this should be fixed now!
