### ISSUE TITLE
nvimage.lib link problems

### ISSUE THREAD

**Issue by arves100** [castano/nvidia-texture-tools#240]
Hi, i'm try to compile DevIL 1.7.8 with nvtt support.

When i go to linking i get: external symbol nv::Array::clear not resolved.
I checked and there's missing this files that are defined in Array.inl but it dosen't load it :/
This is issued by ImageIO.cpp in NVImage

I'm compiling with v120_xp in Win32.
I used CMake 3.5.2 for generate the projects

**Comment by castano** [comment]
Thanks. This should be fixed now.
