### ISSUE TITLE
Invalid sizeof(long) check in Atomic.h

### ISSUE THREAD

**Issue by k6project** [castano/nvidia-texture-tools#261]
Hi,
I was trying to build nvtt on OSX (64bit), and stumbled upon the following in src/nvthread/Atomic.h:186

NV_COMPILER_CHECK(sizeof(uint32) == sizeof(long));

Such check is also performed in this file earlier for MSVC (where it would be valid). As OSC Clang is not LLP64, this will always fail.

Could it be that the check is misplaced?

**Comment by KonajuGames** [comment]
Seems quite important, because this makes builds on Mac fail.  Simple repro steps.  Just run `./configure` then `make`. Latest macOS Sierra (10.12.5), latest Xcode (8.3.3).  The offending static_assert was merged in 4 fours ago.

**Comment by shougan** [comment]
I have same issue OSX Sierra 10.12.5 Xcode 8.2

**Comment by ediazfer** [comment]
I've just stumbled on this issue.
It looks like (long) is not directly used on the OSX/IOS specific part of the code.
I've removed the assert and the compiler gives no warning (ie: about mismatch pointer target size)
It worked for my purpose.

[nvcompress-osx.patch.txt](https://github.com/castano/nvidia-texture-tools/files/1190273/nvcompress-osx.patch.txt)

**Comment by castano** [comment]
Sorry it took so long to fix this. The invalid assert was just a copy&paste error from the windows code.
