### ISSUE TITLE
Wrong sub-sampling in alphaTestCoverage

### ISSUE THREAD

**Issue by OICW** [castano/nvidia-texture-tools#266]
In the current implmentation of `FloatImage::alphaTestCoverage` there's this for loop that doesn't seem to be doing what it shoud:

```
const uint n = 8;
for (float fy = 0.5f/n; fy < 1.0f; fy++) {
  for (float fx = 0.5f/n; fx < 1.0f; fx++) {
    // subsample 4 texels
  }
}
```
Judging by the return statement `return coverage / float(w * h * n * n);` it's meant to run 8x8 times to produce nicely subsampled result but in reality both loops make just a single iteration. as the `fx++` statement increments fx by 1.0 thus failing the condition on the subsequent iteration.

**Comment by castano** [comment]
Good catch! Thanks for reporting the issue!

**Comment by OICW** [comment]
No problem, glad I could help.
