### ISSUE TITLE
Make pImpl-classes actually pimpl

### ISSUE THREAD

**Issue by StefanBruens** [castano/nvidia-texture-tools#278]
The NVTT_DECLARE_PIMPL macro uses
 
    public:
        struct Private;
        Private& m;

Although this moves the data members out of the class, it still exposes the Private class, e.g. everwhere the interface class is used the declaration of Private has to be included.

Changing the macro definition to:

    struct Private;
    Private * m_p;

avoids exposing the private interface.

Changing (T& m) to (T* m) is fine ABI wise, as both use T* internally.

**Comment by castano** [comment]
This is not correct. Closing.

**Comment by StefanBruens** [comment]
Thanks for the elaborate explanation ...

**Comment by castano** [comment]
Private is forward declared and not exposed regardless of whether you use a pointer or a reference. The definition of the inner Private class should never be included. The only header that you need to include is "nvtt/nvtt.h".
