### ISSUE TITLE
[regression] The file 'anyfile.jpg' is not a supported image type.

### ISSUE THREAD

**Issue by axredneck** [castano/nvidia-texture-tools#281]
nvcompress writes that "The file 'somefile.jpg' is not a supported image type." no matter what file i try to compress. I tried various png and jpg textures.
`[redneck@pylesos squish]$ nvcompress -bc1 ./WALL51_2.png`
`NVIDIA Texture Tools 2.1.0 - Copyright NVIDIA Corporation 2007`
`The file './WALL51_2.png' is not a supported image type.`
`[redneck@pylesos squish]$ nvcompress -bc1 /home/redneck/xfiles/с/squish/libSquish.png`
`NVIDIA Texture Tools 2.1.0 - Copyright NVIDIA Corporation 2007`
`The file '/home/redneck/xfiles/с/squish/libSquish.png' is not a supported image type.`
`[redneck@pylesos squish]$ nvcompress /home/redneck/xfiles/mypic/textures/001.normal.jpg`
`NVIDIA Texture Tools 2.1.0 - Copyright NVIDIA Corporation 2007`
`The file '/home/redneck/xfiles/mypic/textures/001.normal.jpg' is not a supported image type.`

**Comment by axredneck** [comment]
It's a regression. Bad commit is 9489aed825c6a0a931dfdd75e8ab6f97292b31a7 or ff3bd55892c80b20a19afab448d0930a0f57d544 , can't check more precisely because 9489aed825c6a0a931dfdd75e8ab6f97292b31a7 doesn't compile.

**Comment by Razende** [comment]
Hey, looks like I have the same problem. When using Ortho4XP

https://github.com/oscarpilote/Ortho4XP/tree/airport_auto_patch 

https://forums.x-plane.org/index.php?/forums/topic/148718-python3-pilimagetk-package-for-manjaro-arch-linux/&do=findComment&comment=1415040

**Comment by nsf** [comment]
Practical fix:

```diff
diff --git a/src/nvconfig.h.in b/src/nvconfig.h.in
index 16da646..866d163 100644
--- a/src/nvconfig.h.in
+++ b/src/nvconfig.h.in
@@ -11,6 +11,7 @@
 #cmakedefine HAVE_DISPATCH_H

 #define HAVE_STBIMAGE
+#define NV_HAVE_STBIMAGE
 //#cmakedefine HAVE_PNG
 //#cmakedefine HAVE_JPEG
 //#cmakedefine HAVE_TIFF
```

**Comment by castano** [comment]
Thanks nsf! I've integrated your fix: 
https://github.com/castano/nvidia-texture-tools/commit/95bd6193cc87f0d9dbf314edec4e23fbf7d9cb79
