### ISSUE TITLE
MinGW build under Windows

### ISSUE THREAD

**Issue by daniilpetrov** [castano/nvidia-texture-tools#302]
Will you append building NVTT in MinGW under Windows? FreeImage and AMD Compressonator libraries which are available for download can be linked in MinGW.

**Comment by daniilpetrov** [comment]
I build NVTT in MinGW, but the compiler says that the Windows-code is not available, for example, #include <intrin.h> and so on.

**Comment by castano** [comment]
Sorry, MinGW is not supported, but I'd be happy to integrate fixes to make it work.
