### ISSUE TITLE
src/nvtt/tools/thumbnailer.cpp fails to build

### ISSUE THREAD

**Issue by zakalawe** [castano/nvidia-texture-tools#311]
It seems recent changes to nv::DirectDrawSurface have broken building of this tool, I fixed a few but not sure what the intention was here; DirectDrawSurface has had many API updates so presumably thumbnail needs major work?

**Comment by zakalawe** [comment]
Just disabled thumbnail build in CMake and the next tool (nvzoom, aka 'resize.cpp') also fails ...

**Comment by castano** [comment]
Sorry for the breakage. I think these errors are fixed now.
