### ISSUE TITLE
RAW-output of a compressed image

### ISSUE THREAD

**Issue by daniilpetrov** [castano/nvidia-texture-tools#319]
Is there a RAW-output of a compressed image for a proprietary (my own) texture container?

**Comment by daniilpetrov** [comment]
To memory!

**Comment by daniilpetrov** [comment]
I meant - without a header.

**Comment by castano** [comment]
Yes, I think the documentation here is still accurate:
https://github.com/castano/nvidia-texture-tools/wiki/ApiDocumentation#output-options
but let me know if it needs more detail!
