### ISSUE TITLE
Master fails to build, claims a file is missing:

### ISSUE THREAD

**Issue by evertvorster** [castano/nvidia-texture-tools#320]
------------------------------------snip--------------------------------
[ 66%] Building CXX object src/nvtt/CMakeFiles/nvtt.dir/CompressorDX9.cpp.o
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/src/nvtt/CompressorDX9.cpp:30:10: fatal error: ClusterFit.h: No such file or directory
   30 | #include "ClusterFit.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/nvtt/CMakeFiles/nvtt.dir/build.make:122: src/nvtt/CMakeFiles/nvtt.dir/CompressorDX9.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:720: src/nvtt/CMakeFiles/nvtt.dir/all] Error 2
make: *** [Makefile:183: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by castano** [comment]
Thanks for the heads up. This is fixed now.
