### ISSUE TITLE
Build errors in etcpack.cxx.o

### ISSUE THREAD

**Issue by evertvorster** [castano/nvidia-texture-tools#321]
[ 80%] Building CXX object src/nvtt/CMakeFiles/nvtt.dir/__/__/extern/etcpack/etcpack.cxx.o
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:162:1: error: a storage class can only be specified for objects and functions
  162 | static enum{PATTERN_H = 0,
      | ^~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:165:1: error: a storage class can only be specified for objects and functions
  165 | static enum{MODE_ETC1, MODE_THUMB_T, MODE_THUMB_H, MODE_PLANAR};
      | ^~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:205:1: error: a storage class can only be specified for objects and functions
  205 | static enum{ETC1_RGB_NO_MIPMAPS,ETC2PACKAGE_RGB_NO_MIPMAPS,ETC2PACKAGE_RGBA_NO_MIPMAPS_OLD,ETC2PACKAGE_RGBA_NO_MIPMAPS,ETC2PACKAGE_RGBA1_NO_MIPMAPS,ETC2PACKAGE_R_NO_MIPMAPS,ETC2PACKAGE_RG_NO_MIPMAPS,ETC2PACKAGE_R_SIGNED_NO_MIPMAPS,ETC2PACKAGE_RG_SIGNED_NO_MIPMAPS,ETC2PACKAGE_sRGB_NO_MIPMAPS,ETC2PACKAGE_sRGBA_NO_MIPMAPS,ETC2PACKAGE_sRGBA1_NO_MIPMAPS};
      | ^~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:206:1: error: a storage class can only be specified for objects and functions
  206 | static enum {MODE_COMPRESS, MODE_UNCOMPRESS, MODE_PSNR};
      | ^~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:207:1: error: a storage class can only be specified for objects and functions
  207 | static enum {SPEED_SLOW, SPEED_FAST, SPEED_MEDIUM};
      | ^~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:208:1: error: a storage class can only be specified for objects and functions
  208 | static enum {METRIC_PERCEPTUAL, METRIC_NONPERCEPTUAL};
      | ^~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:209:1: error: a storage class can only be specified for objects and functions
  209 | static enum {CODEC_ETC, CODEC_ETC2};
      | ^~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:247:1: error: a storage class can only be specified for objects and functions
  247 | static enum {GL_R=0x1903,GL_RG=0x8227,GL_RGB=0x1907,GL_RGBA=0x1908};
      | ^~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx: In function 'bool readSrcFile(char*, uint8*&, int&, int&, int&, int&)':
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:462:15: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  462 |  if(fileExist("tmp.ppm"))
      |               ^~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:494:14: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  494 |  if(fReadPPM("tmp.ppm",w1,h1,img,bitrate))
      |              ^~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx: In function 'bool readSrcFileNoExpand(char*, uint8*&, int&, int&)':
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:560:15: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  560 |  if(fileExist("tmp.ppm"))
      |               ^~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:590:14: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  590 |  if(fReadPPM("tmp.ppm",w1,h1,img,8))
      |              ^~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx: In function 'void packBlock59T(uint8 (*)[3], uint8, unsigned int, unsigned int&, unsigned int&)':
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:130:34: warning: result of '(2 << 31)' requires 34 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
  130 | #define MASK(size, startpos) (((2<<(size-1))-1) << SHIFT(size,startpos))
      |                                 ~^~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:131:63: note: in expansion of macro 'MASK'
  131 | #define PUTBITS( dest, data, size, startpos) dest = ((dest & ~MASK(size, startpos)) | ((data << SHIFT(size, startpos)) & MASK(size,startpos)))
      |                                                               ^~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:6392:2: note: in expansion of macro 'PUTBITS'
 6392 |  PUTBITS( compressed2, pixel_indices, 32, 31);
      |  ^~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:130:34: warning: result of '(2 << 31)' requires 34 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
  130 | #define MASK(size, startpos) (((2<<(size-1))-1) << SHIFT(size,startpos))
      |                                 ~^~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:131:122: note: in expansion of macro 'MASK'
  131 | #define PUTBITS( dest, data, size, startpos) dest = ((dest & ~MASK(size, startpos)) | ((data << SHIFT(size, startpos)) & MASK(size,startpos)))
      |                                                                                                                          ^~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:6392:2: note: in expansion of macro 'PUTBITS'
 6392 |  PUTBITS( compressed2, pixel_indices, 32, 31);
      |  ^~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx: In function 'unsigned int compressBlockTHUMB58HFastestPerceptual1000(uint8*, int, int, int, int, unsigned int&, unsigned int&)':
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:130:34: warning: result of '(2 << 31)' requires 34 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
  130 | #define MASK(size, startpos) (((2<<(size-1))-1) << SHIFT(size,startpos))
      |                                 ~^~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:131:63: note: in expansion of macro 'MASK'
  131 | #define PUTBITS( dest, data, size, startpos) dest = ((dest & ~MASK(size, startpos)) | ((data << SHIFT(size, startpos)) & MASK(size,startpos)))
      |                                                               ^~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:6985:2: note: in expansion of macro 'PUTBITS'
 6985 |  PUTBITS( compressed2, best_pixel_indices, 32, 31);
      |  ^~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:130:34: warning: result of '(2 << 31)' requires 34 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
  130 | #define MASK(size, startpos) (((2<<(size-1))-1) << SHIFT(size,startpos))
      |                                 ~^~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:131:122: note: in expansion of macro 'MASK'
  131 | #define PUTBITS( dest, data, size, startpos) dest = ((dest & ~MASK(size, startpos)) | ((data << SHIFT(size, startpos)) & MASK(size,startpos)))
      |                                                                                                                          ^~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:6985:2: note: in expansion of macro 'PUTBITS'
 6985 |  PUTBITS( compressed2, best_pixel_indices, 32, 31);
      |  ^~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx: In function 'double compressBlockTHUMB58HFastest(uint8*, int, int, int, int, unsigned int&, unsigned int&)':
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:130:34: warning: result of '(2 << 31)' requires 34 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
  130 | #define MASK(size, startpos) (((2<<(size-1))-1) << SHIFT(size,startpos))
      |                                 ~^~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:131:63: note: in expansion of macro 'MASK'
  131 | #define PUTBITS( dest, data, size, startpos) dest = ((dest & ~MASK(size, startpos)) | ((data << SHIFT(size, startpos)) & MASK(size,startpos)))
      |                                                               ^~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:7062:2: note: in expansion of macro 'PUTBITS'
 7062 |  PUTBITS( compressed2, best_pixel_indices, 32, 31);
      |  ^~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:130:34: warning: result of '(2 << 31)' requires 34 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
  130 | #define MASK(size, startpos) (((2<<(size-1))-1) << SHIFT(size,startpos))
      |                                 ~^~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:131:122: note: in expansion of macro 'MASK'
  131 | #define PUTBITS( dest, data, size, startpos) dest = ((dest & ~MASK(size, startpos)) | ((data << SHIFT(size, startpos)) & MASK(size,startpos)))
      |                                                                                                                          ^~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:7062:2: note: in expansion of macro 'PUTBITS'
 7062 |  PUTBITS( compressed2, best_pixel_indices, 32, 31);
      |  ^~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx: In function 'double compressBlockTHUMB58HAlpha(uint8*, uint8*, int, int, int, int, unsigned int&, unsigned int&)':
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:130:34: warning: result of '(2 << 31)' requires 34 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
  130 | #define MASK(size, startpos) (((2<<(size-1))-1) << SHIFT(size,startpos))
      |                                 ~^~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:131:63: note: in expansion of macro 'MASK'
  131 | #define PUTBITS( dest, data, size, startpos) dest = ((dest & ~MASK(size, startpos)) | ((data << SHIFT(size, startpos)) & MASK(size,startpos)))
      |                                                               ^~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:7126:2: note: in expansion of macro 'PUTBITS'
 7126 |  PUTBITS( compressed2, best_pixel_indices, 32, 31);
      |  ^~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:130:34: warning: result of '(2 << 31)' requires 34 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
  130 | #define MASK(size, startpos) (((2<<(size-1))-1) << SHIFT(size,startpos))
      |                                 ~^~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:131:122: note: in expansion of macro 'MASK'
  131 | #define PUTBITS( dest, data, size, startpos) dest = ((dest & ~MASK(size, startpos)) | ((data << SHIFT(size, startpos)) & MASK(size,startpos)))
      |                                                                                                                          ^~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:7126:2: note: in expansion of macro 'PUTBITS'
 7126 |  PUTBITS( compressed2, best_pixel_indices, 32, 31);
      |  ^~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx: In function 'double compressBlockTHUMB58HFast(uint8*, int, int, int, int, unsigned int&, unsigned int&)':
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:130:34: warning: result of '(2 << 31)' requires 34 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
  130 | #define MASK(size, startpos) (((2<<(size-1))-1) << SHIFT(size,startpos))
      |                                 ~^~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:131:63: note: in expansion of macro 'MASK'
  131 | #define PUTBITS( dest, data, size, startpos) dest = ((dest & ~MASK(size, startpos)) | ((data << SHIFT(size, startpos)) & MASK(size,startpos)))
      |                                                               ^~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:7240:2: note: in expansion of macro 'PUTBITS'
 7240 |  PUTBITS( compressed2, best_pixel_indices, 32, 31);
      |  ^~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:130:34: warning: result of '(2 << 31)' requires 34 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
  130 | #define MASK(size, startpos) (((2<<(size-1))-1) << SHIFT(size,startpos))
      |                                 ~^~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:131:122: note: in expansion of macro 'MASK'
  131 | #define PUTBITS( dest, data, size, startpos) dest = ((dest & ~MASK(size, startpos)) | ((data << SHIFT(size, startpos)) & MASK(size,startpos)))
      |                                                                                                                          ^~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:7240:2: note: in expansion of macro 'PUTBITS'
 7240 |  PUTBITS( compressed2, best_pixel_indices, 32, 31);
      |  ^~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx: In function 'void readAlpha(uint8*&, int&, int&, int&, int&)':
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:8516:11: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 8516 |  fReadPGM("alpha.pgm",width,height,tempdata,wantedBitDepth);
      |           ^~~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx: In function 'void writeOutputFile(char*, uint8*, uint8*, int, int)':
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:9460:13: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 9460 |   fWritePPM("tmp.ppm",width,height,img,8,false);
      |             ^~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:9465:13: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 9465 |   fWritePPM("tmp.ppm",width,height,img,16,false);
      |             ^~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:9468:13: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 9468 |   fWritePGM("alphaout.pgm",width,height,alphaimg,false,8);
      |             ^~~~~~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:9470:13: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 9470 |   fWritePGM("alphaout.pgm",width,height,alphaimg,false,16);
      |             ^~~~~~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:9506:13: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 9506 |    fReadPPM("tmp.ppm", rw, rh, pixelsRGB, 8);
      |             ^~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:9507:22: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 9507 |             fReadPGM("alphaout.pgm", rw, rh, pixelsA, 8);
      |                      ^~~~~~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx: In function 'unsigned int compressBlockTHUMB58HExhaustivePerceptual(uint8*, int, int, int, int, unsigned int&, unsigned int&, unsigned int)':
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:130:34: warning: result of '(2 << 31)' requires 34 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
  130 | #define MASK(size, startpos) (((2<<(size-1))-1) << SHIFT(size,startpos))
      |                                 ~^~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:131:63: note: in expansion of macro 'MASK'
  131 | #define PUTBITS( dest, data, size, startpos) dest = ((dest & ~MASK(size, startpos)) | ((data << SHIFT(size, startpos)) & MASK(size,startpos)))
      |                                                               ^~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:14888:2: note: in expansion of macro 'PUTBITS'
14888 |  PUTBITS( compressed2, best_pixel_indices, 32, 31);
      |  ^~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:130:34: warning: result of '(2 << 31)' requires 34 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
  130 | #define MASK(size, startpos) (((2<<(size-1))-1) << SHIFT(size,startpos))
      |                                 ~^~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:131:122: note: in expansion of macro 'MASK'
  131 | #define PUTBITS( dest, data, size, startpos) dest = ((dest & ~MASK(size, startpos)) | ((data << SHIFT(size, startpos)) & MASK(size,startpos)))
      |                                                                                                                          ^~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:14888:2: note: in expansion of macro 'PUTBITS'
14888 |  PUTBITS( compressed2, best_pixel_indices, 32, 31);
      |  ^~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx: In function 'unsigned int compressBlockTHUMB58HExhaustive(uint8*, int, int, int, int, unsigned int&, unsigned int&, unsigned int)':
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:130:34: warning: result of '(2 << 31)' requires 34 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
  130 | #define MASK(size, startpos) (((2<<(size-1))-1) << SHIFT(size,startpos))
      |                                 ~^~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:131:63: note: in expansion of macro 'MASK'
  131 | #define PUTBITS( dest, data, size, startpos) dest = ((dest & ~MASK(size, startpos)) | ((data << SHIFT(size, startpos)) & MASK(size,startpos)))
      |                                                               ^~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:15099:2: note: in expansion of macro 'PUTBITS'
15099 |  PUTBITS( compressed2, best_pixel_indices, 32, 31);
      |  ^~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:130:34: warning: result of '(2 << 31)' requires 34 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
  130 | #define MASK(size, startpos) (((2<<(size-1))-1) << SHIFT(size,startpos))
      |                                 ~^~~~~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:131:122: note: in expansion of macro 'MASK'
  131 | #define PUTBITS( dest, data, size, startpos) dest = ((dest & ~MASK(size, startpos)) | ((data << SHIFT(size, startpos)) & MASK(size,startpos)))
      |                                                                                                                          ^~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/extern/etcpack/etcpack.cxx:15099:2: note: in expansion of macro 'PUTBITS'
15099 |  PUTBITS( compressed2, best_pixel_indices, 32, 31);
      |  ^~~~~~~
make[2]: *** [src/nvtt/CMakeFiles/nvtt.dir/build.make:369: src/nvtt/CMakeFiles/nvtt.dir/__/__/extern/etcpack/etcpack.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:720: src/nvtt/CMakeFiles/nvtt.dir/all] Error 2
make: *** [Makefile:183: all] Error 2
==> ERROR: A failure occurred in build().

**Comment by castano** [comment]
Please, provide compiler version and target OS.

**Comment by evertvorster** [comment]
Hi there!
The OS is Arch Linux

gcc --version
gcc (GCC) 10.1.0

uname -a
Linux Vorster.Home 5.4.49-1-lts #1 SMP Thu, 25 Jun 2020 00:14:43 +0000 x86_64 GNU/Linux

Build instructions:
  cmake -DCMAKE_INSTALL_PREFIX=/usr  \
        -DCMAKE_C_FLAGS:STRING="${CFLAGS} -msse4.1" \
        -DCMAKE_CXX_FLAGS:STRING="${CXXFLAGS} -msse4.1" \
        ../nvidia-texture-tools/
  make

It's worth noting that these very same build instructions work on git revision
1e0653901271b64c0803abb06ef9c46153831c8e

To build it now, I just roll back to that fairly new revision. So, it's something that has changed since then. 
I hope all this helps?

-Evert-

**Comment by castano** [comment]
Well, I'm not sure what's causing the build problem, but I should not be building etcpack anyway. I removed it from the build and that should hopefully fix the problem.

**Comment by evertvorster** [comment]
In deed it does. Just compiled the Arch Linux version against latest master. I'll update the package in the repositories now. 

Kind regards,-Evert-
