### ISSUE TITLE
Relation to NVIDIA Texture Tools exporter 

### ISSUE THREAD

**Issue by SukantPal** [castano/nvidia-texture-tools#323]
Is this software the same as this: https://developer.nvidia.com/nvidia-texture-tools-exporter? Thanks for the clarification.

**Comment by castano** [comment]
Unfortunately, no. The closed source nvidia texture tools are probably based on an earlier versions of the open source nvidia texture tools, with additional changes that are not public. I know that's really confusing, but I don't work at nvidia, I don't have any control over what nvidia does with their tools, and why they chose to discontinue their open source efforts. 

From a cursory look at the DXT1 compressor, the performance is good, but quality is mediocre, which is unfortunate. The BC6-7 compressors are hopefully better, the open source codecs in NVTT need a lot of work to be useful in practical scenarios and you are probably better off using Rich Geldreichs (https://github.com/richgel999/bc7enc) or AMDs compressors (https://compressonator.readthedocs.io/en/latest/developer_sdk/cmp_core/).
