### ISSUE TITLE
Compile error on master branch. 

### ISSUE THREAD

**Issue by evertvorster** [castano/nvidia-texture-tools#325]
Hi there!

There is a compile error on the master branch. It was actually reported to me some days ago, but I forgot to push it upstream. 
This is on Arch Linux. 

Here is the error:
[ 27%] Building CXX object src/nvcore/CMakeFiles/nvcore.dir/Debug.cpp.o
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/src/nvcore/Debug.cpp:1018:8: error: 'getEmptyVAList' declared as function returning an array
 1018 | static va_list getEmptyVAList(va_list list, ...)
      |        ^~~~~~~
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/src/nvcore/Debug.cpp: In function 'void nv::debug::dumpCallstack(nv::MessageHandler*, int)':
/data/OS/aur/nvidia-texture-tools-git/src/nvidia-texture-tools/src/nvcore/Debug.cpp:1038:17: error: 'getEmptyVAList' was not declared in this scope
 1038 |         empty = getEmptyVAList(empty);
      |                 ^~~~~~~~~~~~~~
make[2]: *** [src/nvcore/CMakeFiles/nvcore.dir/build.make:82: src/nvcore/CMakeFiles/nvcore.dir/Debug.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:599: src/nvcore/CMakeFiles/nvcore.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error making: %!s(func() string=0x556cf0536bb0)

**Comment by evertvorster** [comment]
The error report was:
"aeb84b5 breaks master again. Had to rollback PKGBUILD to using commit snapshots, again."

**Comment by akb825** [comment]
I'm getting the same problem. One workaround would be to only compile the getEmptyVAList() function on Windows, but realistically the current functionality is a hack that can fail even with MSVC if they make some adjustments to the compiler. The proper solution would be to adjust the code so it doesn't need to create an empty va_list to begin with.

**Comment by akb825** [comment]
I have a PR to fix the Linux build errors I've seen here: https://github.com/castano/nvidia-texture-tools/pull/328
