### ISSUE TITLE
For distribution please recompile nvtt library (Windows) with more recent Visual Studio

### ISSUE THREAD

**Issue by natgla** [castano/nvidia-texture-tools#326]
Hello,
I am from Microsoft Visual C++ team. 
I see that you distribute nvtt library (and some other ones?) compiled with /GL with an old compiler. Couple of years ago we introduced a breaking change in the internal representation; unfortunately we didn't notice in time that it's breaking.
Now fresh compiler crashes while trying to compile such library as a part of other projects.
I am going to fix the crash, but the fix can only be not to crash but to report an error, new compiler won't accept older libraries, they will have to be rebuilt anyway.

Here is one of the reports to us about the crash: https://developercommunity.visualstudio.com/content/problem/1110057/fatal-error-c1001-internal-compiler-error-8.html

Thank you,
Natalia Glagoleva, MSVC

**Comment by natgla** [comment]
I added a workaround in the compiler, and with the new release old libraries should be usable

**Comment by castano** [comment]
Thanks for letting me know about this issue. I've just created a new release that should not have this problem: 
https://github.com/castano/nvidia-texture-tools/releases/tag/2.1.2
