### ISSUE TITLE
BC7 compression is very slow

### ISSUE THREAD

**Issue by akb825** [castano/nvidia-texture-tools#327]
The BC7 compression is extremely slow. For example, an image that takes ~1.4 s to compress as BC1 takes almost 32 minutes to compress for a single thread. Even when multithreading the compression, it still takes a considerable amount of time at almost 8 minutes with 12 threads.

**Comment by castano** [comment]
This is a known problem. The BC7 compressor in NVTT was a reference encoder, intended to explore the quality that the format could achieve, but not intended to be used in production.

There are many other BC7 encoders out there. I would highly recommend Rich Geldreich's BC7 encoder:

https://github.com/richgel999/bc7enc

It's very easy to integrate, seems fast, and relatively high quality, even though it only targets a few of the BC7 modes. I'd love to write a new BC7 encoder at some point, but in the meantime I'd gladly accept patches integrating this or other encoders in NVTT.
